# Change these first
owner: flexjr # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Flex Jr - App
    url: https://app.flexjr.one/
  - name: Flex Jr - API
    url: https://api.flexjr.one/healthz
  - name: Flex Jr - MySQL
    url: https://api.flexjr.one/frappez
  - name: Flex Jr - Redis
    url: https://api.flexjr.one/redisz
  - name: Flex Jr - Admin
    url: https://admin.flexjr.one/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.flexjr.one
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flex Jr
  introTitle: "Uptime monitoring for Flex Jr’s apps and services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
